runtime: nodejs20
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

env_variables:
  NODE_ENV: "production"

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto 